apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-Mego-setting
spec:
  forms:
    - group: header
      label: 首图
      formSchema:
        - $formkit: radio
          name: cover
          label: 显示首图
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: text
          name: title
          label: 站点标题
          help: 自定义标题，默认采用站点名称
        - $formkit: text
          name: description
          label: 站点描述
          help: 自定义描述，默认采用站点名称
        - $formkit: text
          name: color
          label: 字体颜色
          help: 自定义颜色，默认采用白色
        - $formkit: attachment
          name: images
          label: 首图背景
          help: 自定义背景，默认采用原始值

    - group: publicity
      label: 推介区
      formSchema:
        - $formkit: radio
          name: switch
          label: 显示区域
          value: false
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: repeater
          name: banners
          label: 推介区-左侧
          help: 自定义首站展示图
          value:
            - url:
            - image:
          children:
            - $formkit: text
              name: url
              label: 链接
            - $formkit: attachment
              name: image
              label: 图片
              help: 分辨率建议：910*250
        - $formkit: radio
          name: widgets
          label: 推介区-右侧
          help: 自定义显示类型
          value: calendar
          options:
            - label: 日历
              value: calendar
            - label: 文章
              value: article
        - $formkit: postSelect
          name: article_post
          label: 推介文章选择
          help: 自定义文章，选用推介文章时生效
          value: ""

    - group: notifacation
      label: 通知区
      formSchema:
        - $formkit: radio
          name: switch
          label: 显示通知
          value: false
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: text
          name: title
          label: 通知内容
          help: 自定义内容，默认为空
    
    - group: sidebar
      label: 侧边栏
      formSchema:
        - $formkit: repeater
          name: widgets
          label: 主页
          value: [ ]
          children:
            - $formkit: select
              name: value
              label: 部件
              options:
                - label: 站点资料
                  value: site
                - label: 热门文章
                  value: hot-articles
                - label: 标签归档
                  value: tag
                - label: 分类归档
                  value: hot-categories
                - label: 图文广告
                  value: advertising
        - $formkit: attachment
          name: images
          label: 广告图片
          help: 自定义图片，分辨率建议：360x270
        - $formkit: repeater
          name: social
          label: 社交媒体
          value: [ ]
          children:
            - $formkit: select
              name: icon
              label: 图标
              options:
                - label: 电子邮箱
                  value: mingcute--mail-line
                - label: 腾讯QQ
                  value: mingcute--qq-line
                - label: 新浪微博
                  value: mingcute--weibo-line
                - label: 哔哩哔哩
                  value: ri--bilibili-line
                - label: 微信
                  value: mingcute--wechat-line
                - label: Telegram
                  value: mingcute--telegram-line
                - label: Facebook
                  value: mingcute--facebook-line
                - label: Youtube
                  value: mingcute--youtube-line
                - label: Twitter
                  value: mingcute--twitter-line
                - label: Github
                  value: mingcute--github-line
                - label: rss
                  value: mingcute--rss-line
            - $formkit: text
              name: name
              label: 名称
            - $formkit: text
              name: url
              label: 链接
              validation: "required"
            - $formkit: radio
              name: url_type
              label: 打开类型
              value: normal
              help: "如果选择了图片类型，那么在点击之后会使用弹框的形式加载"
              options:
                - label: 跳转链接
                  value: normal
                - label: 图片
                  value: image

    - group: other_card
      label: 侧边(其它)
      formSchema:
        - $formkit: repeater
          name: widgets
          label: 主页
          value: [ ]
          children:
            - $formkit: select
              name: value
              label: 部件
              options:
                - label: 站点资料
                  value: site
                - label: 热门文章
                  value: hot-articles
                - label: 标签归档
                  value: tag
                - label: 分类归档
                  value: hot-categories
                - label: 图文广告
                  value: advertising

    - group: links
      label: 友链
      formSchema:
        - $formkit: radio
          name: style
          label: 友链样式
          help: 友链显示样式          
          value: normal
          options:
            - label: 传统样式
              value: normal
            - label: 卡片样式
              value: card
        - $formkit: code
          name: title
          label: 自定义友链说明
          help: 自定义内容，默认为空时则不显示
          value: ""
          height: 200px
          language: html